apiVersion: v1
kind: ConfigMap
metadata:
  name: node-dns
data:
  # ref. https://github.com/cybozu-go/cke/blob/3b4a6f4469c40e02301a97ae5e1188bbacd19bca/op/nodedns/nodedns.go#L19
  unbound.conf: |
    server:
      do-daemonize: no
      #interface: 0.0.0.0
      interface: 127.0.0.1
      interface-automatic: yes
      access-control: 0.0.0.0/0 allow
      chroot: ""
      username: ""
      directory: "/etc/unbound"
      logfile: ""
      use-syslog: no
      log-time-ascii: yes
      log-queries: yes
      log-replies: yes
      log-local-actions: yes
      log-servfail: yes
      num-threads: 4
      incoming-num-tcp: 1000
      outgoing-num-tcp: 1000
      num-queries-per-thread: 4096
      outgoing-range: 8192
      rrset-roundrobin: yes
      extended-statistics: yes
      rrset-cache-size: 256m
      rrset-cache-slabs: 4
      msg-cache-size: 256m
      msg-cache-slabs: 4
      infra-cache-slabs: 4
      key-cache-slabs: 4
      so-rcvbuf: 4m
      pidfile: "/tmp/unbound.pid"
      infra-host-ttl: 60
      prefetch: yes
      tcp-upstream: yes
      so-reuseport: yes
      local-zone: "10.in-addr.arpa." transparent
      local-zone: "168.192.in-addr.arpa." transparent
      local-zone: "16.172.in-addr.arpa." transparent
      local-zone: "17.172.in-addr.arpa." transparent
      local-zone: "18.172.in-addr.arpa." transparent
      local-zone: "19.172.in-addr.arpa." transparent
      local-zone: "20.172.in-addr.arpa." transparent
      local-zone: "21.172.in-addr.arpa." transparent
      local-zone: "22.172.in-addr.arpa." transparent
      local-zone: "23.172.in-addr.arpa." transparent
      local-zone: "24.172.in-addr.arpa." transparent
      local-zone: "25.172.in-addr.arpa." transparent
      local-zone: "26.172.in-addr.arpa." transparent
      local-zone: "27.172.in-addr.arpa." transparent
      local-zone: "28.172.in-addr.arpa." transparent
      local-zone: "29.172.in-addr.arpa." transparent
      local-zone: "30.172.in-addr.arpa." transparent
      local-zone: "31.172.in-addr.arpa." transparent
    remote-control:
      control-enable: yes
      control-interface: /var/run/unbound/unbound.sock
      control-use-cert: no

