# ref. https://github.com/cybozu-go/cke/blob/3b4a6f4469c40e02301a97ae5e1188bbacd19bca/static/node-dns.yml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: node-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      appname: node-dns
  template:
    metadata:
      labels:
        appname: node-dns
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 1
      containers:
        - name: unbound
          # https://github.com/cybozu-go/cke/blob/3b4a6f4469c40e02301a97ae5e1188bbacd19bca/images.go#L18C32-L18C63
          image: quay.io/cybozu/unbound:1.17.1.4
          args:
            - -c
            - /etc/unbound/unbound.conf
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - all
            readOnlyRootFilesystem: true
          readinessProbe:
            tcpSocket:
              port: 53
              host: localhost
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 53
              host: localhost
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 6
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
            - name: var-run-unbound
              mountPath: /var/run/unbound
        - name: reload
          # https://github.com/cybozu-go/cke/blob/3b4a6f4469c40e02301a97ae5e1188bbacd19bca/images.go#L18C32-L18C63
          image: quay.io/cybozu/unbound:1.17.1.4
          command:
          - /usr/local/bin/reload-unbound
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
            - name: var-run-unbound
              mountPath: /var/run/unbound
      volumes:
        - name: config-volume
          configMap:
            name: node-dns
            items:
            - key: unbound.conf
              path: unbound.conf
        - name: var-run-unbound
          emptyDir: {}
